---
- hosts: host1
  become: yes
  tasks:
    - name: Install packages
      apt:
        name: "nginx"
        state: "present"
    - name: Start Apache server
      service:
        name: nginx
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/

- hosts: host1
  become: yes
  tasks:
    - name: Deploy static website
      script: backup.sh

- hosts: host1
  become: yes
  tasks:
    - name: List all files
      command: ls -lrt
